export const ScreenName = {
    Splash : 'Splash',
    Welcome : 'Welcome',
    ChooseEmployee : 'ChooseEmployee',
    ChooseLoginType : 'ChooseLoginType',
    LoginScreen : 'LoginScreen',
    ForgotPassword : 'ForgotPassword',
    RegisterScreen : 'RegisterScreen',
    TermsAndCondition :  'TermsAndCondition',
    EmployHome : 'EmployHome',
    FileScreen : 'FileScreen',
    ShareView : 'ShareView',
    PaySlipView : 'PaySlipView',
    DaysLeave : 'DaysLeave',
    LogOut : 'LogOut',
    NotificationView : 'NotificationView',
    FullNotificationView : 'FullNotificationView',
    EmployerHome : 'EmployerHome',
    EmployerProfile : 'EmployerProfile',
    AddNewEmployee : 'AddNewEmployee',
    MyProfile : 'MyProfileScreen',
    UpdateProfile : 'UpdateProfile',
    DeleteAccount : 'Delete Account',
    Termination : 'Termination',
    ReasonsTermination : 'ReasonsTermination',
    TerminatoinDoc : 'TerminatoinDoc',
    JobDetailsTitle : 'JobDetailsTitle',
    WorkDay : 'WorkDay',
    PattenOfWork : 'PattenOfWork',
    TermAndCondition : 'TermAndCondition',
    EmployeeForgotPassword: 'EmployeeForgotPassword',
    AddDayLeave : 'AddDayLeave',
    PdfViewer : 'PdfViewer',
    LeaveType : 'LeaveType',
    EditLeave : 'EditLeave',
    EditEmployeeProfile : 'EditEmployeeProfile',
    ViewOrEditLeave : 'ViewOrEditLeave',
    Webview: 'Webview',
}